import "../globals.css";
import { Providers } from "./provider";

export const metadata = {
  title: "Drivyx",
  // description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
