import Footer from "@/ui/Footer";
import Navbar from "@/ui/Navbar";
import "../globals.css";
import { Providers } from "./provider";

export const metadata = {
  title: "Drixyv",
  // description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
