"use client";

import Sidebar from "@/components/Profile/Sidebar";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  GridItem,
} from "@chakra-ui/react";
import React, { useState } from "react";
import Dashboard from "./(dashboard)/Dashboard";
import Profile from "./(profile)/Profile";
import Projects from "./(projects)/Projects";
import { ChevronRightIcon } from "@chakra-ui/icons";
import { NAV_DASHBOARD } from "@/constants/NAV_DASHBOARD";

// export const metadata = {
//   title: "Drixyv | Dashboard",
//   // description: "Generated by Next + Sanity",
// };

function DashboardLayoutRoot() {
  const [sideNav, setSideNav] = useState("");

  const renderMain = () => {
    switch (sideNav) {
      case "dashboard":
        return <Dashboard />;
      case "profile":
        return <Profile />;
      case "project":
        return <Projects />;
      default:
        return <Dashboard />;
    }
  };

  const renderBreadcrumb = () => {
    switch (sideNav) {
      case "profile":
        return (
          <BreadcrumbItem isCurrentPage={true}>
            <BreadcrumbLink>Profile</BreadcrumbLink>
          </BreadcrumbItem>
        );
      case "project":
        return (
          <BreadcrumbItem isCurrentPage={true}>
            <BreadcrumbLink>Project</BreadcrumbLink>
          </BreadcrumbItem>
        );
      case "example":
        return (
          <BreadcrumbItem isCurrentPage={true}>
            <BreadcrumbLink>Example</BreadcrumbLink>
          </BreadcrumbItem>
        );
    }
  };

  return (
    <>
      <GridItem area={"header"} bgColor={"gray.100"}>
        <Breadcrumb
          mx={12}
          my={4}
          spacing="8px"
          separator={<ChevronRightIcon color="gray.500" />}
        >
          <BreadcrumbItem>
            <BreadcrumbLink href={"/dashboard"} fontWeight={600}>
              Dashboard
            </BreadcrumbLink>
          </BreadcrumbItem>
          {renderBreadcrumb()}
        </Breadcrumb>
      </GridItem>

      <GridItem area={"nav"}>
        <Sidebar setSideNav={setSideNav} />
      </GridItem>
      <GridItem area={"main"} w={"100%"} bgColor={"gray.100"}>
        {renderMain()}
      </GridItem>
    </>
  );
}

export default DashboardLayoutRoot;
